## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [2]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [3]:
# your code here
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)), 
    ('ReLU', nn.ReLU()), 
    ('output', nn.Linear(2, 2)),
    ('tanh', nn.Tanh())
]))

In [5]:
print(model1)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=2, out_features=2, bias=True)
  (tanh): Tanh()
)


In [7]:
# your code here
data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [8]:
# your code here
data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [11]:
# your code here
criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1) 

In [ ]:
# your code here
# Train the model
for epoch in range(10000):
    outputs1 = model1(data_in1)
    loss1 = criterion1(outputs1, data_target1)
    
    optimizer1.zero_grad()  
    loss1.backward()          
    optimizer1.step()         
    
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss1.item()} Accuracy: {accuracy1*100}%')
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

Epoch 1000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 2000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 3000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 4000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 5000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 6000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 7000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 8000 Loss: 0.16411197185516357 Accuracy: 75.0%
Epoch 9000 Loss: 0.16411195695400238 Accuracy: 75.0%
Epoch 10000 Loss: 0.16411195695400238 Accuracy: 75.0%


In [17]:
# your code here
# visualize the resuts
print(outputs1)
predicted1 = torch.round(outputs1)
correct1 = (predicted1 == data_target1).all(dim=1).sum()
total1 = data_target1.size(0)
accuracy1 = correct1 / total1
print(f'Model Accuracy: {accuracy1*100}%')

tensor([[-0.2405,  0.5000],
        [ 0.2405,  0.5000],
        [ 0.2405,  0.5000],
        [ 0.6268,  0.5000]], grad_fn=<TanhBackward0>)
Model Accuracy: 75.0%


In [14]:
# your code here
# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Model weights:
hidden.weight tensor([[-0.6085, -0.4645],
        [ 0.6628,  0.6628]])
hidden.bias tensor([-0.4656,  0.2353])
output.weight tensor([[-1.7507e-01,  7.4034e-01],
        [-5.2577e-01, -6.3373e-06]])
output.bias tensor([-0.4196,  0.5493])


In [18]:
# your code here
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)), 
    ('ReLU', nn.ReLU()), 
    ('output', nn.Linear(3, 2)),
    ('tanh', nn.Tanh())
]))

In [19]:
print(model2)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (tanh): Tanh()
)


In [20]:
criterion2 = nn.MSELoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1) 

In [ ]:
for epoch in range(10000):
    outputs2 = model2(data_in1)
    loss2 = criterion2(outputs2, data_target1)
    
    optimizer2.zero_grad()  
    loss2.backward()          
    optimizer2.step()
    
    predicted_classes2 = (outputs2.round() == data_target1)
    accuracy2 = predicted_classes2.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss2.item()} Accuracy: {accuracy2*100}%')  
    if accuracy2 == 1:
        print(f"Model 2 reached 100% accuracy at epoch {epoch+1}")
        break

Epoch 1000 Loss: 0.21875 Accuracy: 25.0%
Epoch 2000 Loss: 0.21875 Accuracy: 25.0%
Epoch 3000 Loss: 0.21875 Accuracy: 25.0%
Epoch 4000 Loss: 0.21875 Accuracy: 25.0%
Epoch 5000 Loss: 0.21875 Accuracy: 25.0%
Epoch 6000 Loss: 0.21875 Accuracy: 25.0%
Epoch 7000 Loss: 0.21875 Accuracy: 25.0%
Epoch 8000 Loss: 0.21875 Accuracy: 25.0%
Epoch 9000 Loss: 0.21875 Accuracy: 25.0%
Epoch 10000 Loss: 0.21875 Accuracy: 25.0%


In [27]:
print(outputs2)
predicted2 = torch.round(outputs2)
correct2 = (predicted2 == data_target1).all(dim=1).sum()
total2 = data_target1.size(0)
accuracy2 = correct2 / total2
print(f'Model Accuracy: {accuracy2*100}%')

tensor([[0.2500, 0.5000],
        [0.2500, 0.5000],
        [0.2500, 0.5000],
        [0.2500, 0.5000]], grad_fn=<TanhBackward0>)
Model Accuracy: 25.0%


In [28]:
# your code here
# print model wights
print(f"Model weights:")
for name, param in model2.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Model weights:
hidden.weight tensor([[ 0.4596, -0.6931],
        [-0.3624, -0.5289],
        [-0.4060,  0.0927]])
hidden.bias tensor([-0.4676, -0.3080, -0.4280])
output.weight tensor([[-0.0185, -0.3656, -0.3467],
        [-0.3888, -0.0592, -0.5313]])
output.bias tensor([0.2554, 0.5493])


In [44]:
model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),
    ('relu1', nn.ReLU()),
    ('hidden2', nn.Linear(4, 4)),
    ('relu2', nn.ReLU()),
    ('output', nn.Linear(4, 2)),
    ('sigmoid', nn.Sigmoid())
]))

In [45]:
criterion3 = nn.MSELoss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1) 

In [46]:
for epoch in range(10000):
    outputs3 = model3(data_in1)
    loss3 = criterion3(outputs3, data_target1)
    
    optimizer3.zero_grad()  
    loss3.backward()          
    optimizer3.step()
    
    predicted_classes3 = (outputs3.round() == data_target1)
    accuracy3 = predicted_classes3.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss3.item()} Accuracy: {accuracy3*100}%')  
    if accuracy3 == 1:
        print(f"Model 3 reached 100% accuracy at epoch {epoch+1}")
        break

Epoch 1000 Loss: 0.21867884695529938 Accuracy: 25.0%
Epoch 2000 Loss: 0.18171478807926178 Accuracy: 50.0%
Model 3 reached 100% accuracy at epoch 2962


In [47]:
print(outputs3)
predicted3 = torch.round(outputs3)
correct3 = (predicted3 == data_target1).all(dim=1).sum()
total3 = data_target1.size(0)
accuracy3 = correct3 / total3
print(f'Model Accuracy: {accuracy3*100}%')

tensor([[0.0681, 0.4795],
        [0.0497, 0.5007],
        [0.0610, 0.9425],
        [0.6981, 0.2683]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%


In [48]:
print(f"Model weights:")
for name, param in model2.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Model weights:
hidden.weight tensor([[ 0.4596, -0.6931],
        [-0.3624, -0.5289],
        [-0.4060,  0.0927]])
hidden.bias tensor([-0.4676, -0.3080, -0.4280])
output.weight tensor([[-0.0185, -0.3656, -0.3467],
        [-0.3888, -0.0592, -0.5313]])
output.bias tensor([0.2554, 0.5493])
